### PR TITLE
Elasticsearch 2.x support

### PR DESCRIPTION
**Pull request by suzuken**
- using Elasticsearch 2.2 Java SDK
- remove some metrics which removed or deprecated in Elasticsearch 2.x

### CODE REVIEW

**Comment by aldrinleal** [comment]
Looks good - but do we need guava or whatever anymore? (remember we're under Java 8)

**Comment by suzuken** [comment]
Thank you for your comment! I'm not familiar with Guava, but it seems useful for testing purpose, isn't it?

And, I misunderstood that Elasticsearch includes com.google.guava v18.0 in it's jar file. So I removed `com.google.guava` from mavan dependencies. It's works fine.

**Comment by suzuken** [comment]
Hmm, looking into [Support for loading a plugin in a client node is missing · Issue #15927 · elastic/elasticsearch](https://github.com/elastic/elasticsearch/issues/15927), it seems that `Nodebuilder` cannot be used in Plugin. I'll trying to use Transport Client instead.

**Comment by aldrinleal** [comment]
I'll go take a look at it, wakarimasu ka?

**Pull request closed without merging**
